# -*- coding: utf-8 -*-
"""Model2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NMJBcuWazhhOlZYRNZXlDiB1ggOMUjDI
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2

os.chdir('/content/drive/My Drive/darknet')

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137

!ln -s '/content/drive/My Drive/' /new8drive

os.chdir('/new8drive/darknet')
!sudo chmod +x darknet
!./darknet

!./darknet detector train data/Lemon_Dataset/image_data.data cfg/yolov4_train.cfg yolov4.conv.137 -dont_show

!./darknet detector train data/Lemon_Dataset/image_data.data cfg/yolov4_train.cfg /new5drive/darknet/backup/yolov4_train_last.weights -dont_show